### PR TITLE
Eslint/prettier+clean up

### LINKED ISSUE #42: ESLint & Prettier
Add 

- [EsLint](https://github.com/eslint/eslint) and 
- [Prettier](https://github.com/prettier/prettier)

to this project, to enforce consistent and uniform code style as well as reduce and prevent errors by enforcing best-practices

### PR DESCRIPTION
**Pull request by mbastian93**
This pull request will add eslint and prettier (fixes #42 ) with respective configurations and plugins and will also fix all resulting errors/problems

### CODE REVIEW

**Comment by mbastian93** [comment]
ToDo:
- [x] install & configure ESlint
- [x] install & configure Prettier
- [ ] rename files containing jsx.syntax
- [ ] Fix problems in all files:
  - [ ] some file

**Comment by mahvaezi** [comment]
When I change the setting of formatter in VSCode and set FormatOnSave= true, it works for me. It means, when I save a change, the file is formatted automatically. But without this configuration I could commit without formatting the code before. The prettier doesn't suggest me to fix problem when I change something.

**Comment by mbastian93** [comment]
> When I change the setting of formatter in VSCode and set FormatOnSave= true, it works for me. It means, when I save a change, the file is formatted automatically. But without this configuration I could commit without formatting the code before. The prettier doesn't suggest me to fix problem when I change something.

I'm not sure if i understand your problem.
For problems/warnings to be shown you have to install the necessary extensions for eslint and prettier for your editor/IDE.
If prettier and/or eslint are installed as dependencies via npm you can also run the command line tools which then print problems/warnings.

**Comment by mahvaezi** [comment]
They are already installed. I also can run the command. But I don’t see any quick fixes from prettier/lint.
Let’s assume a developer forgot to run the command and committed his changes. So we still don‘t have the improvement this pull- Request should bring.

**Comment by mbastian93** [comment]
Ok now i understand. This pull request does not add any automatic fixes, but with the rules defined for eslint and prettier, the IDE can highlight problems in the code - provided, the necessary extensions are installed.
When #44 has been merged, lines that do not comply to these rules will be annotated when a pull-request is opened. In that case, the check will fail, indicating, that some cleaning-up should be done.

**Comment by mahvaezi** [comment]
I see! I didn’t read the #44 yet.
Sounds good to me.

**Review by mahvaezi — APPROVED** [review]

**Pull request merged**
